0: Wandb run: atmorep-i1u3vy7t-18679070
0: l50048:2860510:2860510 [0] NCCL INFO Bootstrap : Using ib0:10.128.11.138<0>
0: l50048:2860510:2860510 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
0: l50048:2860510:2860510 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
0: l50048:2860510:2860510 [0] NCCL INFO NET/Plugin: Using internal network plugin.
0: l50048:2860510:2860510 [0] NCCL INFO cudaDriverVersion 12060
0: NCCL version 2.21.5+cuda12.4
0: l50048:2860510:2860971 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [RO]; OOB ib0:10.128.11.138<0>
0: l50048:2860510:2860971 [0] NCCL INFO Using non-device net plugin version 0
0: l50048:2860510:2860971 [0] NCCL INFO Using network IB
0: l50048:2860510:2860971 [0] NCCL INFO DMA-BUF is available on GPU device 0
0: l50048:2860510:2860971 [0] NCCL INFO ncclCommInitRank comm 0x55555f1030f0 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 3000 commId 0x836adaaa50a84306 - Init START
0: l50048:2860510:2860971 [0] NCCL INFO Setting affinity for GPU 0 to ffff0000,00000000,00000000,00000000,ffff0000,00000000
0: l50048:2860510:2860971 [0] NCCL INFO comm 0x55555f1030f0 rank 0 nRanks 1 nNodes 1 localRanks 1 localRank 0 MNNVL 0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 00/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 01/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 02/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 03/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 04/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 05/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 06/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 07/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 08/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 09/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 10/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 11/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 12/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 13/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 14/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 15/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 16/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 17/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 18/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 19/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 20/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 21/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 22/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 23/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 24/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 25/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 26/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 27/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 28/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 29/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 30/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Channel 31/32 :    0
0: l50048:2860510:2860971 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
0: l50048:2860510:2860971 [0] NCCL INFO P2P Chunksize set to 131072
0: l50048:2860510:2860971 [0] NCCL INFO Connected all rings
0: l50048:2860510:2860971 [0] NCCL INFO Connected all trees
0: l50048:2860510:2860971 [0] NCCL INFO 32 coll channels, 32 collnet channels, 0 nvls channels, 32 p2p channels, 32 p2p channels per peer
0: l50048:2860510:2860971 [0] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
0: l50048:2860510:2860971 [0] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
0: l50048:2860510:2860971 [0] NCCL INFO ncclCommInitRank comm 0x55555f1030f0 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 3000 commId 0x836adaaa50a84306 - Init COMPLETE
0: Running Evaluate.evaluate with mode = forecast
0: Available keys in the Zarr dataset: ['data', 'data_sfc', 'lats', 'lons', 'time']
0: self.ds['data'] : (105192, 7, 5, 721, 1440) :: (105192,)
0: self.lats : (721,)
0: self.lons : (1440,)
0: Available keys in the Zarr dataset: ['data', 'data_sfc', 'lats', 'lons', 'time']
0: self.ds['data'] : (105192, 7, 5, 721, 1440) :: (105192,)
0: self.lats : (721,)
0: self.lons : (1440,)
0: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3'] 0
0: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3'] 0
0: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3'] 0
0: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3'] 0
0: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3'] 0
0: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3'] 0
0: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3'] 0
0: Loaded model id = hjbmsjft.
0: with_ddp : True
0: num_accs_per_task : 4
0: par_rank : 0
0: par_size : 1
0: fields : [['velocity_u', [1, 1024, ['velocity_v', 'temperature'], 0, ['j8dwr5qj', -2]], [96, 105, 114, 123, 137], [12, 3, 6], [3, 18, 18], [0.5, 0.9, 0.2, 0.05]], ['velocity_v', [1, 1024, ['velocity_u', 'temperature'], 0, ['0tlnm5up', -2]], [96, 105, 114, 123, 137], [12, 3, 6], [3, 18, 18], [0.5, 0.9, 0.2, 0.05]], ['specific_humidity', [1, 1024, ['velocity_u', 'velocity_v', 'temperature'], 0, ['v63l01zu', -2]], [96, 105, 114, 123, 137], [12, 3, 6], [3, 18, 18], [0.5, 0.9, 0.2, 0.05]], ['velocity_z', [1, 1024, ['velocity_u', 'velocity_v', 'temperature'], 0, ['9l1errbo', -2]], [96, 105, 114, 123, 137], [12, 3, 6], [3, 18, 18], [0.5, 0.9, 0.2, 0.05]], ['temperature', [1, 1024, ['velocity_u', 'velocity_v', 'specific_humidity'], 0, ['7ojls62c', -2]], [96, 105, 114, 123, 137], [12, 2, 4], [3, 27, 27], [0.5, 0.9, 0.2, 0.05], 'Local'], ['total_precip', [1, 1024, ['velocity_u', 'velocity_v', 'velocity_z', 'specific_humidity'], 0], [0], [12, 6, 12], [3, 9, 9], [0.25, 0.9, 0.1, 0.05]], ['t2m', [1, 1024, ['velocity_u', '
0: velocity_v', 'velocity_z', 'specific_humidity'], 0], [0], [12, 2, 4], [3, 27, 27], [0.5, 0.9, 0.2, 0.05], 'Local']]
0: fields_prediction : [['velocity_u', 0.125], ['velocity_v', 0.125], ['specific_humidity', 0.05], ['velocity_z', 0.01], ['temperature', 0.1], ['total_precip', 0.01], ['t2m', 0.58]]
0: fields_targets : []
0: years_train : [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
0: years_val : [2021]
0: month : None
0: geo_range_sampling : [[0.0, 360.0], [0.0, 360.0]]
0: time_sampling : 1
0: torch_seed : 5521420987310380410
0: batch_size_validation : 1
0: batch_size : 96
0: num_epochs : 128
0: num_samples_per_epoch : 480
0: num_samples_validate : 128
0: num_loader_workers : 5
0: size_token_info : 8
0: size_token_info_net : 16
0: grad_checkpointing : True
0: with_cls : False
0: with_mixed_precision : True
0: with_layernorm : True
0: coupling_num_heads_per_field : 1
0: dropout_rate : 0.05
0: with_qk_lnorm : True
0: encoder_num_layers : 6
0: encoder_num_heads : 16
0: encoder_num_mlp_layers : 2
0: encoder_att_type : dense
0: decoder_num_layers : 6
0: decoder_num_heads : 16
0: decoder_num_mlp_layers : 2
0: decoder_self_att : False
0: decoder_cross_att_ratio : 0.5
0: decoder_cross_att_rate : 1.0
0: decoder_att_type : dense
0: net_tail_num_nets : 16
0: net_tail_num_layers : 0
0: losses : ['mse_ensemble', 'stats']
0: optimizer_zero : False
0: lr_start : 1e-05
0: lr_max : 2e-05
0: lr_min : 1e-05
0: weight_decay : 0.025
0: lr_decay_rate : 1.025
0: lr_start_epochs : 3
0: model_log_frequency : 256
0: BERT_strategy : forecast
0: forecast_num_tokens : 2
0: BERT_fields_synced : False
0: BERT_mr_max : 2
0: log_test_num_ranks : 4
0: save_grads : False
0: profile : False
0: test_initial : False
0: attention : False
0: rng_seed : None
0: with_wandb : True
0: slurm_job_id : 18679070
0: wandb_id : i1u3vy7t
0: file_path : /work/ab1412/atmorep/data/era5_y2010_2020_res25_with_t2m.zarr
0: n_size : [36, 13.5, 27.0]
0: model_id : hjbmsjft
0: with_pytest : True
0: lat_sampling_weighted : False
0: it == 0 and starting val norms printouts
0: [DEBUG] PREDICTIONS VALIDATION BATCH
0: Normalised validation prediction values for 't2m' with shape: torch.Size([16, 2187])
0:          min = -0.810, max = 0.239, mean = -0.157
0:          sample (first 20): tensor([-0.5267, -0.5789, -0.5474, -0.5437, -0.5992, -0.5550, -0.5481, -0.5617, -0.5798, -0.6182, -0.5328, -0.5682,
0:         -0.5906, -0.5309, -0.5556, -0.5891, -0.5322, -0.5590, -0.6009, -0.6084])
0: validation loss for strategy=forecast at epoch 0 : 0.2916009724140167
0: validation loss for velocity_u : 0.03436174988746643
0: validation loss for velocity_v : 0.06756513565778732
0: validation loss for specific_humidity : 0.02680317685008049
0: validation loss for velocity_z : 0.5203872919082642
0: validation loss for temperature : 0.06308189779520035
0: validation loss for total_precip : 0.7627044320106506
0: validation loss for t2m : 0.5663036108016968
0: ============================= test session starts ==============================
0: platform linux -- Python 3.10.10, pytest-8.3.4, pluggy-1.5.0
0: rootdir: /work/ab1412
0: collected 3 items
0: 
0: atmorep/tests/validation_test.py Sample 37, Level 96: Timestamp 2021-07-10 05:00:00, Shape (54, 108)
0: Sample 12, Level 96: Timestamp 2021-04-09 12:00:00, Shape (54, 108)
0: Sample 95, Level 96: Timestamp 2021-07-16 14:00:00, Shape (54, 108)
0: Sample 108, Level 96: Timestamp 2021-05-14 09:00:00, Shape (54, 108)
0: Sample 100, Level 96: Timestamp 2021-11-14 22:00:00, Shape (54, 108)
0: .F
0: 
0: =================================== FAILURES ===================================
0: _______________________________ test_coordinates _______________________________
0: 
0: field = 'velocity_u', model_id = 'i1u3vy7t', BERT = False, epoch = 0
0: 
0:     def test_coordinates(field, model_id, BERT, epoch = 0):
0:         """
0:         Check that coordinates match between target and prediction.
0:         Check also that latitude and longitudes are in geographical coordinates
0:         50 random samples.
0:         """
0:     
0:         store_t = zarr.ZipStore(atmorep_target().format(model_id, model_id, str(epoch).zfill(5)))
0:         target = zarr.group(store_t)
0:     
0:         store_p = zarr.ZipStore(atmorep_pred().format(model_id, model_id, str(epoch).zfill(5)))
0:         pred = zarr.group(store_p)
0:     
0:         nsamples = min(len(target[field]), 50)
0:         samples = rnd.sample(range(len(target[field])), nsamples)
0:         #levels = [int(f.split("=")[1]) for f in target[f"{field}/sample=00000"]] if BERT else target[f"{field}/sample=00000"].ml[:]
0:         ##### new levels for surface fields - added this test ####
0:         if 'ml' in target[f"{field}/sample=00000"]:
0:             levels = target[f"{field}/sample=00000"].ml[:]
0:         else:
0:             levels = [0]  # For surface fields
0:         #####
0: >       print(f"Field: {field}, levels: {levels}, level: {level}, level_idx: {level_idx}, samples: {samples}")
0: E       UnboundLocalError: local variable 'level' referenced before assignment
0: 
0: atmorep/tests/validation_test.py:164: UnboundLocalError
0: =========================== short test summary info ============================
0: FAILED atmorep/tests/validation_test.py::test_coordinates - UnboundLocalError...
0: !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
0: ========================= 1 failed, 1 passed in 8.11s ==========================
0: ============================= test session starts ==============================
0: platform linux -- Python 3.10.10, pytest-8.3.4, pluggy-1.5.0
0: rootdir: /work/ab1412
0: collected 3 items
0: 
0: atmorep/tests/validation_test.py Sample 38, Level 96: Timestamp 2021-11-01 03:00:00, Shape (54, 108)
0: Sample 105, Level 96: Timestamp 2021-04-22 03:00:00, Shape (54, 108)
0: Sample 94, Level 96: Timestamp 2021-10-06 10:00:00, Shape (54, 108)
0: Sample 63, Level 96: Timestamp 2021-04-19 15:00:00, Shape (54, 108)
0: Sample 56, Level 96: Timestamp 2021-05-27 19:00:00, Shape (54, 108)
0: .F
0: 
0: =================================== FAILURES ===================================
0: _______________________________ test_coordinates _______________________________
0: 
0: field = 'velocity_v', model_id = 'i1u3vy7t', BERT = False, epoch = 0
0: 
0:     def test_coordinates(field, model_id, BERT, epoch = 0):
0:         """
0:         Check that coordinates match between target and prediction.
0:         Check also that latitude and longitudes are in geographical coordinates
0:         50 random samples.
0:         """
0:     
0:         store_t = zarr.ZipStore(atmorep_target().format(model_id, model_id, str(epoch).zfill(5)))
0:         target = zarr.group(store_t)
0:     
0:         store_p = zarr.ZipStore(atmorep_pred().format(model_id, model_id, str(epoch).zfill(5)))
0:         pred = zarr.group(store_p)
0:     
0:         nsamples = min(len(target[field]), 50)
0:         samples = rnd.sample(range(len(target[field])), nsamples)
0:         #levels = [int(f.split("=")[1]) for f in target[f"{field}/sample=00000"]] if BERT else target[f"{field}/sample=00000"].ml[:]
0:         ##### new levels for surface fields - added this test ####
0:         if 'ml' in target[f"{field}/sample=00000"]:
0:             levels = target[f"{field}/sample=00000"].ml[:]
0:         else:
0:             levels = [0]  # For surface fields
0:         #####
0: >       print(f"Field: {field}, levels: {levels}, level: {level}, level_idx: {level_idx}, samples: {samples}")
0: E       UnboundLocalError: local variable 'level' referenced before assignment
0: 
0: atmorep/tests/validation_test.py:164: UnboundLocalError
0: =========================== short test summary info ============================
0: FAILED atmorep/tests/validation_test.py::test_coordinates - UnboundLocalError...
0: !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
0: ========================= 1 failed, 1 passed in 0.37s ==========================
0: ============================= test session starts ==============================
0: platform linux -- Python 3.10.10, pytest-8.3.4, pluggy-1.5.0
0: rootdir: /work/ab1412
0: collected 3 items
0: 
0: atmorep/tests/validation_test.py Sample 68, Level 96: Timestamp 2021-06-04 22:00:00, Shape (54, 108)
0: Sample 30, Level 96: Timestamp 2021-07-11 11:00:00, Shape (54, 108)
0: Sample 95, Level 96: Timestamp 2021-07-16 14:00:00, Shape (54, 108)
0: Sample 124, Level 96: Timestamp 2021-05-02 04:00:00, Shape (54, 108)
0: Sample 81, Level 96: Timestamp 2021-10-16 08:00:00, Shape (54, 108)
0: .F
0: 
0: =================================== FAILURES ===================================
0: _______________________________ test_coordinates _______________________________
0: 
0: field = 'specific_humidity', model_id = 'i1u3vy7t', BERT = False, epoch = 0
0: 
0:     def test_coordinates(field, model_id, BERT, epoch = 0):
0:         """
0:         Check that coordinates match between target and prediction.
0:         Check also that latitude and longitudes are in geographical coordinates
0:         50 random samples.
0:         """
0:     
0:         store_t = zarr.ZipStore(atmorep_target().format(model_id, model_id, str(epoch).zfill(5)))
0:         target = zarr.group(store_t)
0:     
0:         store_p = zarr.ZipStore(atmorep_pred().format(model_id, model_id, str(epoch).zfill(5)))
0:         pred = zarr.group(store_p)
0:     
0:         nsamples = min(len(target[field]), 50)
0:         samples = rnd.sample(range(len(target[field])), nsamples)
0:         #levels = [int(f.split("=")[1]) for f in target[f"{field}/sample=00000"]] if BERT else target[f"{field}/sample=00000"].ml[:]
0:         ##### new levels for surface fields - added this test ####
0:         if 'ml' in target[f"{field}/sample=00000"]:
0:             levels = target[f"{field}/sample=00000"].ml[:]
0:         else:
0:             levels = [0]  # For surface fields
0:         #####
0: >       print(f"Field: {field}, levels: {levels}, level: {level}, level_idx: {level_idx}, samples: {samples}")
0: E       UnboundLocalError: local variable 'level' referenced before assignment
0: 
0: atmorep/tests/validation_test.py:164: UnboundLocalError
0: =========================== short test summary info ============================
0: FAILED atmorep/tests/validation_test.py::test_coordinates - UnboundLocalError...
0: !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
0: ========================= 1 failed, 1 passed in 0.57s ==========================
0: ============================= test session starts ==============================
0: platform linux -- Python 3.10.10, pytest-8.3.4, pluggy-1.5.0
0: rootdir: /work/ab1412
0: collected 3 items
0: 
0: atmorep/tests/validation_test.py Sample 45, Level 96: Timestamp 2021-09-12 22:00:00, Shape (54, 108)
0: Sample 100, Level 96: Timestamp 2021-11-14 22:00:00, Shape (54, 108)
0: Sample 76, Level 96: Timestamp 2021-04-03 23:00:00, Shape (54, 108)
0: Sample 95, Level 96: Timestamp 2021-07-16 14:00:00, Shape (54, 108)
0: Sample 103, Level 96: Timestamp 2021-11-13 08:00:00, Shape (54, 108)
0: .F
0: 
0: =================================== FAILURES ===================================
0: _______________________________ test_coordinates _______________________________
0: 
0: field = 'velocity_z', model_id = 'i1u3vy7t', BERT = False, epoch = 0
0: 
0:     def test_coordinates(field, model_id, BERT, epoch = 0):
0:         """
0:         Check that coordinates match between target and prediction.
0:         Check also that latitude and longitudes are in geographical coordinates
0:         50 random samples.
0:         """
0:     
0:         store_t = zarr.ZipStore(atmorep_target().format(model_id, model_id, str(epoch).zfill(5)))
0:         target = zarr.group(store_t)
0:     
0:         store_p = zarr.ZipStore(atmorep_pred().format(model_id, model_id, str(epoch).zfill(5)))
0:         pred = zarr.group(store_p)
0:     
0:         nsamples = min(len(target[field]), 50)
0:         samples = rnd.sample(range(len(target[field])), nsamples)
0:         #levels = [int(f.split("=")[1]) for f in target[f"{field}/sample=00000"]] if BERT else target[f"{field}/sample=00000"].ml[:]
0:         ##### new levels for surface fields - added this test ####
0:         if 'ml' in target[f"{field}/sample=00000"]:
0:             levels = target[f"{field}/sample=00000"].ml[:]
0:         else:
0:             levels = [0]  # For surface fields
0:         #####
0: >       print(f"Field: {field}, levels: {levels}, level: {level}, level_idx: {level_idx}, samples: {samples}")
0: E       UnboundLocalError: local variable 'level' referenced before assignment
0: 
0: atmorep/tests/validation_test.py:164: UnboundLocalError
0: =========================== short test summary info ============================
0: FAILED atmorep/tests/validation_test.py::test_coordinates - UnboundLocalError...
0: !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
0: ========================= 1 failed, 1 passed in 0.33s ==========================
0: ============================= test session starts ==============================
0: platform linux -- Python 3.10.10, pytest-8.3.4, pluggy-1.5.0
0: rootdir: /work/ab1412
0: collected 3 items
0: 
0: atmorep/tests/validation_test.py Sample 43, Level 96: Timestamp 2021-07-21 23:00:00, Shape (54, 108)
0: Sample 89, Level 96: Timestamp 2021-04-08 09:00:00, Shape (54, 108)
0: Sample 19, Level 96: Timestamp 2021-04-28 00:00:00, Shape (54, 108)
0: Sample 68, Level 96: Timestamp 2021-06-04 22:00:00, Shape (54, 108)
0: Sample 35, Level 96: Timestamp 2021-03-11 22:00:00, Shape (54, 108)
0: .F
0: 
0: =================================== FAILURES ===================================
0: _______________________________ test_coordinates _______________________________
0: 
0: field = 'temperature', model_id = 'i1u3vy7t', BERT = False, epoch = 0
0: 
0:     def test_coordinates(field, model_id, BERT, epoch = 0):
0:         """
0:         Check that coordinates match between target and prediction.
0:         Check also that latitude and longitudes are in geographical coordinates
0:         50 random samples.
0:         """
0:     
0:         store_t = zarr.ZipStore(atmorep_target().format(model_id, model_id, str(epoch).zfill(5)))
0:         target = zarr.group(store_t)
0:     
0:         store_p = zarr.ZipStore(atmorep_pred().format(model_id, model_id, str(epoch).zfill(5)))
0:         pred = zarr.group(store_p)
0:     
0:         nsamples = min(len(target[field]), 50)
0:         samples = rnd.sample(range(len(target[field])), nsamples)
0:         #levels = [int(f.split("=")[1]) for f in target[f"{field}/sample=00000"]] if BERT else target[f"{field}/sample=00000"].ml[:]
0:         ##### new levels for surface fields - added this test ####
0:         if 'ml' in target[f"{field}/sample=00000"]:
0:             levels = target[f"{field}/sample=00000"].ml[:]
0:         else:
0:             levels = [0]  # For surface fields
0:         #####
0: >       print(f"Field: {field}, levels: {levels}, level: {level}, level_idx: {level_idx}, samples: {samples}")
0: E       UnboundLocalError: local variable 'level' referenced before assignment
0: 
0: atmorep/tests/validation_test.py:164: UnboundLocalError
0: =========================== short test summary info ============================
0: FAILED atmorep/tests/validation_test.py::test_coordinates - UnboundLocalError...
0: !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
0: ========================= 1 failed, 1 passed in 0.35s ==========================
0: ============================= test session starts ==============================
0: platform linux -- Python 3.10.10, pytest-8.3.4, pluggy-1.5.0
0: rootdir: /work/ab1412
0: collected 3 items
0: 
0: atmorep/tests/validation_test.py Sample 13, Level 96: Timestamp 2021-06-25 12:00:00, Shape (54, 108)
0: Sample 125, Level 96: Timestamp 2021-09-12 01:00:00, Shape (54, 108)
0: Sample 82, Level 96: Timestamp 2021-02-22 12:00:00, Shape (54, 108)
0: Sample 6, Level 96: Timestamp 2021-09-01 23:00:00, Shape (54, 108)
0: Sample 86, Level 96: Timestamp 2021-08-17 17:00:00, Shape (54, 108)
0: .F
0: 
0: =================================== FAILURES ===================================
0: _______________________________ test_coordinates _______________________________
0: 
0: field = 'total_precip', model_id = 'i1u3vy7t', BERT = False, epoch = 0
0: 
0:     def test_coordinates(field, model_id, BERT, epoch = 0):
0:         """
0:         Check that coordinates match between target and prediction.
0:         Check also that latitude and longitudes are in geographical coordinates
0:         50 random samples.
0:         """
0:     
0:         store_t = zarr.ZipStore(atmorep_target().format(model_id, model_id, str(epoch).zfill(5)))
0:         target = zarr.group(store_t)
0:     
0:         store_p = zarr.ZipStore(atmorep_pred().format(model_id, model_id, str(epoch).zfill(5)))
0:         pred = zarr.group(store_p)
0:     
0:         nsamples = min(len(target[field]), 50)
0:         samples = rnd.sample(range(len(target[field])), nsamples)
0:         #levels = [int(f.split("=")[1]) for f in target[f"{field}/sample=00000"]] if BERT else target[f"{field}/sample=00000"].ml[:]
0:         ##### new levels for surface fields - added this test ####
0:         if 'ml' in target[f"{field}/sample=00000"]:
0:             levels = target[f"{field}/sample=00000"].ml[:]
0:         else:
0:             levels = [0]  # For surface fields
0:         #####
0: >       print(f"Field: {field}, levels: {levels}, level: {level}, level_idx: {level_idx}, samples: {samples}")
0: E       UnboundLocalError: local variable 'level' referenced before assignment
0: 
0: atmorep/tests/validation_test.py:164: UnboundLocalError
0: =========================== short test summary info ============================
0: FAILED atmorep/tests/validation_test.py::test_coordinates - UnboundLocalError...
0: !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
0: ========================= 1 failed, 1 passed in 0.34s ==========================
0: ============================= test session starts ==============================
0: platform linux -- Python 3.10.10, pytest-8.3.4, pluggy-1.5.0
0: rootdir: /work/ab1412
0: collected 3 items
0: 
0: atmorep/tests/validation_test.py Sample 21, Level 96: Timestamp 2021-06-29 08:00:00, Shape (54, 108)
0: Sample 56, Level 96: Timestamp 2021-05-27 19:00:00, Shape (54, 108)
0: Sample 58, Level 96: Timestamp 2021-04-26 12:00:00, Shape (54, 108)
0: Sample 31, Level 96: Timestamp 2021-07-11 17:00:00, Shape (54, 108)
0: Sample 26, Level 96: Timestamp 2021-01-29 01:00:00, Shape (54, 108)
0: .F
0: 
0: =================================== FAILURES ===================================
0: _______________________________ test_coordinates _______________________________
0: 
0: field = 't2m', model_id = 'i1u3vy7t', BERT = False, epoch = 0
0: 
0:     def test_coordinates(field, model_id, BERT, epoch = 0):
0:         """
0:         Check that coordinates match between target and prediction.
0:         Check also that latitude and longitudes are in geographical coordinates
0:         50 random samples.
0:         """
0:     
0:         store_t = zarr.ZipStore(atmorep_target().format(model_id, model_id, str(epoch).zfill(5)))
0:         target = zarr.group(store_t)
0:     
0:         store_p = zarr.ZipStore(atmorep_pred().format(model_id, model_id, str(epoch).zfill(5)))
0:         pred = zarr.group(store_p)
0:     
0:         nsamples = min(len(target[field]), 50)
0:         samples = rnd.sample(range(len(target[field])), nsamples)
0:         #levels = [int(f.split("=")[1]) for f in target[f"{field}/sample=00000"]] if BERT else target[f"{field}/sample=00000"].ml[:]
0:         ##### new levels for surface fields - added this test ####
0:         if 'ml' in target[f"{field}/sample=00000"]:
0:             levels = target[f"{field}/sample=00000"].ml[:]
0:         else:
0:             levels = [0]  # For surface fields
0:         #####
0: >       print(f"Field: {field}, levels: {levels}, level: {level}, level_idx: {level_idx}, samples: {samples}")
0: E       UnboundLocalError: local variable 'level' referenced before assignment
0: 
0: atmorep/tests/validation_test.py:164: UnboundLocalError
0: =========================== short test summary info ============================
0: FAILED atmorep/tests/validation_test.py::test_coordinates - UnboundLocalError...
0: !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
0: ========================= 1 failed, 1 passed in 0.34s ==========================
0: time 337.71730160713196
0: [1;34mwandb[0m:
0: [1;34mwandb[0m: You can sync this run to the cloud by running:
0: [1;34mwandb[0m: [1mwandb sync /work/ab1412/atmorep/wandb/offline-run-20250728_132217-i1u3vy7t[0m
0: [1;34mwandb[0m: Find logs at: [1;35mwandb/offline-run-20250728_132217-i1u3vy7t/logs[0m
0: l50048:2860510:2860974 [0] NCCL INFO [Service thread] Connection closed by localRank 0
0: l50048:2860510:2861750 [0] NCCL INFO comm 0x55555f1030f0 rank 0 nranks 1 cudaDev 0 busId 3000 - Abort COMPLETE
